---

- name: Install golang via homebrew
  homebrew:
    name=go
    install_options={{ golang_brew_options }}
  tags:
    - brew
    - golang

- name: Go path dir
  file:
    path={{ gopath_dir }}
    state=directory
  tags:
    - golang

- name: Install golang packages
  command: go get {{ item }}
  with_items: golang_packages
  ignore_errors: yes
  tags:
    - golang
