---

- name: Get vimfiles repo
  git:
    repo={{ vimfiles_repo }}
    dest={{ workspace_dir }}/vimfiles
  tags:
    - vimfiles

- name: Install vimfiles
  command: "{{ vimfiles_install_cmd }}"
  args:
    chdir: "{{ vimfiles_dir }}"
    creates: "{{ vimfiles_installed_file }}"
  tags:
    - vimfiles

- name: Install YCM
  command: "{{ ycm_install_cmd }}"
  args:
    chdir: "{{ ycm_bundle_dir }}"
    creates: "{{ ycm_installed_file }}"
  tags:
    - vimfiles
