---

- hosts: localhost
  connection: local
  gather_facts: false
  roles:
    - base
    - tmux
    - dotfiles
    - vimfiles
    - ruby
    - erlang
    - elixir
    - golang
    - rust
    - nodejs
    - python
    - docker
