---

- name: Nvm setup script
  template:
    src: nvm-setup.j2
    dest: "{{ home_dir }}/bin/setup-nvm"
    mode: 0755
  tags:
    - nodejs
    - nvm

- name: Run nvm setup script
  command: "{{ home_dir }}/bin/setup-nvm"
  tags:
    - nodejs
    - nvm

- name: Make yarn dir
  file:
    path: "{{ home_dir }}/.yarn"
    state: directory
  tags:
    - nodejs
    - yarn

- name: NPM config
  template:
    src: npmrc.j2
    dest: "{{ home_dir }}/.npmrc"
    mode: 0755
  tags:
    - nodejs
    - npm
