---

- name: Upgrade pip
  command: "pip install --upgrade pip"
  tags:
    - python

- name: Install python packages
  pip:
    name: "{{ item }}"
    state: latest
  become: yes
  become_method: sudo
  with_items: "{{ python_packages }}"
  tags:
    - python
