---

brew_install_cmd: "ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\""
brew_bin: "/usr/local/bin/brew"
brew_cask_bin: "/usr/local/bin/brew-cask"
brew_base_packages:
  - name: autoconf
  - name: automake
  - name: bash
  - name: bash-completion
  - name: bazaar
  - name: cmatrix
  - name: cmake
  - name: coreutils
  - name: cscope
  - name: ctags
  - name: curl
  - name: findutils
  - name: fontconfig
  - name: freetype
  - name: fswatch
  - name: gettext
  - name: git
    install_options: "with-gettext,with-pcre,with-persistent-https,with-blk-sha1"
  - name: go-app-engine-64
  - name: gnu-sed
  - name: gnu-tar
  - name: graphviz
  - name: heroku-toolbelt
  - name: htop
  - name: hub
  - name: influxdb
  - name: jq
  - name: leveldb
  - name: libevent
  - name: libffi
  - name: libidn
  - name: libmemcached
  - name: libmpc
  - name: libpng
  - name: libxml2
  - name: libyaml
  - name: lua
  - name: luajit
  - name: makedepend
  - name: memcached
  - name: mercurial
  - name: moreutils
  - name: ocaml
  - name: opam
  - name: phantomjs
  - name: postgresql
  - name: pyenv
  - name: pyenv-virtualenv
  - name: python
  - name: readline
  - name: redis
  - name: s3cmd
  - name: snappy
  - name: sqlite
  - name: the_silver_searcher
  - name: tree
  - name: wget
  - name: zeromq
brew_cask_applications:
  - name: alfred
  - name: appzapper
  - name: arduino
  - name: arq
  - name: atom
  - name: bartender
  - name: caffeine
  - name: cloak
  - name: dropbox
  - name: firefox
  - name: flux
  - name: google-chrome
  - name: google-hangouts
  - name: gpgtools
  - name: hipchat
  - name: imagealpha
  - name: imageoptim
  - name: insomniax
  - name: istat-menus
  - name: iterm2
  - name: java
  - name: julia
  - name: keyboard-cleaner
  - name: keyboardcleantool
  - name: little-snitch
  - name: packer
  - name: spotify
  - name: sublime-text
  - name: terraform
  - name: the-unarchiver
  - name: time-out
  - name: torbrowser
  - name: transmission
  - name: tunnelblick
  - name: vagrant
  - name: vault
  - name: virtualbox
  - name: viscosity
  - name: vmware-fusion
  - name: vlc
  - name: youll-never-take-me-alive
brew_cask_install_updates:
  - name: atom
  - name: julia
  - name: nomad
    force: "--force"
  - name: otto
    force: "--force"
  - name: packer
    force: "--force"
  - name: terraform
    force: "--force"
  - name: vault
    force: "--force"
