---

- name: Install rbenv via homebrew
  homebrew:
    name={{ item.name }} state=latest
  with_items: ruby_brew_packages
  tags:
    - brew
    - ruby

- name: Install ruby versions
  command: rbenv install {{ item }} creates={{ home_dir }}/.rbenv/versions/{{ item }}
  with_items: ruby_versions
  tags: ruby

- name: Check ruby global file exists
  stat: path={{ ruby_global_file }}
  register: ruby_global_exists
  tags:
    - ruby

- name: Set global ruby version
  command: rbenv global {{ ruby_global }}
  when: not ruby_global_exists.stat.exists or lookup('file', ruby_global_file) != ruby_global
  tags:
    - ruby

- name: Install ruby gems
  gem: name={{ item }}
  with_items: ruby_gems
  tags:
    - ruby
